src/imagetagger/annotations/urls.py
from django.urls import path

from . import views

app_name = 'annotations'
urlpatterns = [
    path('export/create/', views.create_exportformat, name='create_exportformat'),
    path('export/<int:format_id>/edit/', views.edit_exportformat, name='edit_exportformat'),
    path('export/<int:format_id>/delete/', views.delete_exportformat, name='delete_exportformat'),
    path('export/<int:export_id>/auth/', views.export_auth, name='export_auth'),
    path('export/<int:export_id>/download/', views.download_export, name='download_export'),
    path('export/<int:image_set_id>/', views.create_export, name='create_export'),
    path('api/export/create/', views.api_create_export, name='api_create_export'),
    path('api/export_format/list/', views.api_get_export_formats, name='api_get_export_formats'),
    path('manage/annotation/<int:image_set_id>/', views.manage_annotations, name='manage_annotations'),
    path('manage/delete/<int:image_set_id>/', views.delete_annotations, name='delete_annotations'),
    path('<int:annotation_id>/delete/', views.delete_annotation, name='delete_annotation'),
    path('<int:image_id>/', views.annotate, name='annotate'),
    path('annotateset/<int:imageset_id>/', views.annotate_set, name='annotate_set'),
    path('<int:annotation_id>/verify/', views.verify, name='verify'),
    path('api/annotation/create/', views.create_annotation, name='create_annotation'),
    path('api/annotation/delete/', views.api_delete_annotation, name='delete_annotation'),
    path('api/annotation/load/', views.load_annotations, name='load_annotations'),  # loads annotations of an image
    path('api/annotation/loadset/', views.load_set_annotations, name='load_set_annotations'),  # loads annotations of an image
    path('api/annotation/loadannotationtypes/', views.load_annotation_types, name='load_annotation_types'),  # loads all active annotation types
    path('api/annotation/loadsuperannotationtypes/', views.load_super_annotation_types, name='load_super_annotation_types'),
    path('api/annotation/loadsetannotationtypes/', views.load_set_annotation_types, name='load_set_annotation_types'),  # loads annotations of an image
    path('api/annotation/loadfilteredset/', views.load_filtered_set_annotations, name='load_filtered_set_annotations'),  # loads filtered annotations of an image
    path('api/annotation/loadone/', views.load_annotation, name='load_annotation'),
    path('api/annotation/loadmultiple/', views.load_multiple_annotations, name='load_multiple_annotations'),
    path('api/annotation/verify/', views.api_verify_annotation, name='verify_annotation'),
    path('api/annotation/update/', views.update_annotation, name='update_annotations'),
    path('api/annotation/blurred_concealed/', views.api_blurred_concealed_annotation, name='blurred_concealed_annotation'),
]

src/imagetagger/base/urls.py
from django.urls import path

from . import views

app_name = 'base'
urlpatterns = [
    path('', views.index, name='index'),
    path('problems/', views.problem_report, name='problem')
]

src/imagetagger/images/urls.py
from django.urls import path

from . import views

app_name = 'images'
urlpatterns = [
    path('', views.index, name='index'),
    path('image/delete/<int:image_id>/', views.delete_images, name='delete_images'),
    path('image/setfree/<int:imageset_id>/', views.set_free, name='setfree_imageset'),
    path('image/upload/<int:imageset_id>/', views.upload_image, name='upload_image'),
    path('image/<int:image_id>/', views.view_image, name='view_image'),
    path('imagelist/<int:image_set_id>/', views.list_images, name='list_images'),
    path('imageset/<int:imageset_id>/label-upload/', views.label_upload, name='label_upload'),
    path('imageset/create/', views.create_imageset, name='create_imageset'),
    path('imageset/<int:imageset_id>/delete/', views.delete_imageset, name='delete_imageset'),
    path('imageset/<int:imageset_id>/pin/', views.toggle_pin_imageset, name='pin_imageset'),
    path('imageset/<int:imageset_id>/edit/', views.edit_imageset, name='edit_imageset'),
    path('imageset/<int:image_set_id>/', views.view_imageset, name='view_imageset'),
    path('imageset/<int:image_set_id>/download/', views.download_imageset_zip, name='download_imageset'),
    path('imageset/explore/', views.explore_imageset, name='explore_imageset'),
    path('imageset/imagetagger_dl_script.py', views.dl_script, name='dl_script'),
    path('api/imageset/load/', views.load_image_set, name='load_image_set'),
    path('api/imageset/tag/add/', views.tag_image_set, name='tag_image_set'),
    path('api/imageset/tag/delete/', views.remove_image_set_tag, name='remove_image_set_tag'),
    path('api/imageset/tag/autocomplete/', views.autocomplete_image_set_tag, name='autocomplete_image_set_tag'),
]

src/imagetagger/urls.py
from django.urls import path, include
from django.contrib import admin
from django.shortcuts import render
from django_registration.backends.activation.views import RegistrationView

from .users.forms import UserRegistrationForm

urlpatterns = [
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/register/', RegistrationView.as_view(form_class=UserRegistrationForm), name='django_registration_register'),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('', include('imagetagger.base.urls')),
    path('admin/', admin.site.urls),
    path('administration/', include('imagetagger.administration.urls')),
    path('annotations/', include('imagetagger.annotations.urls')),
    path('images/', include('imagetagger.images.urls')),
    path('users/', include('imagetagger.users.urls')),
    path('tagger_messages/', include('imagetagger.tagger_messages.urls')),
    path('tools/', include('imagetagger.tools.urls')),
]


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None
    """
    use_sentry = False
    sentry_dsn = None
    event_id = None
    try:
        import sentry_sdk
        if sentry_sdk.Hub.current.client:
            use_sentry = True
            sentry_dsn = sentry_sdk.Hub.current.client.dsn
            event_id = sentry_sdk.last_event_id()
    except ImportError:
        pass

    return render(request, '500.html', status=500, context={
        'use_sentry': use_sentry,
        'sentry_dsn': sentry_dsn,
        'event_id': event_id,
    })

src/imagetagger/users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('api/user/autocomplete/', views.user_autocomplete, name='user_autocomplete'),
    path('team/<int:team_id>/', views.view_team, name='team'),
    path('team/create/', views.create_team, name='create_team'),
    path('team/explore/', views.explore_team, name='explore_team'),
    path('team/<int:team_id>/add/', views.add_team_member, name='add_team_member'),
    path('team/<int:team_id>/leave/', views.leave_team, name='leave_team'),
    path('team/<int:team_id>/leave/<int:user_id>/', views.leave_team, name='leave_team'),
    path('team/<int:team_id>/grant_admin/<int:user_id>/', views.grant_team_admin, name='grant_team_admin'),
    path('team/<int:team_id>/revoke_admin/<int:user_id>/', views.revoke_team_admin, name='revoke_team_admin'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('user/<int:user_id>/delete/', views.delete_account, name='delete_account'),
    path('user/explore/', views.explore_user, name='explore_user'),
]

src/imagetagger/base/models.py
# Create your models here.

src/imagetagger/tools/models.py
from typing import Set

from imagetagger.users.models import Team
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class Tool(models.Model):
    name = models.CharField(max_length=100)
    filename = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=False)
    team = models.ForeignKey(Team,
                             on_delete=models.SET_NULL,
                             related_name='tool_team',
                             null=True,
                             blank=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.SET_NULL,
                                related_name='tool_creator',
                                null=True,
                                blank=True)

    @property
    def internal_filename(self):
        return '{0}_{1}'.format(self.id, self.name)

    def get_perms(self, user: get_user_model()) -> Set[str]:
        """Get all permissions of the user."""
        perms = set()
        if self.creator is not None and self.creator.id is user.id:
            perms.update({
                'edit_tool',
                'delete_tool',
                'download_tool',
                'see_tool',
            })
        if self.team is not None:
            if self.team.is_admin(user):
                perms.update({
                    'edit_tool',
                    'delete_tool',
                    'download_tool',
                    'see_tool',
                })
            if self.team.is_member(user):
                perms.update({
                    'download_tool',
                    'see_tool',
                })
        if self.public:
            perms.update({
                'download_tool',
                'see_tool',
            })
        return perms

    def has_perm(self, permission: str, user: get_user_model()) -> bool:
        """Check whether user has a specified permission."""
        return permission in self.get_perms(user)


class ToolVote(models.Model):
    class Meta:
        unique_together = [
            'tool',
            'user',
        ]

    tool = models.ForeignKey(
        Tool, on_delete=models.CASCADE, related_name='tool')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True)
    time = models.DateTimeField(auto_now_add=True)
    positive = models.BooleanField(default=0)

src/imagetagger/annotations/forms.py
from django import forms

from imagetagger.annotations.models import ExportFormat


class ExportFormatCreationForm(forms.ModelForm):
    class Meta:
        model = ExportFormat
        fields = [
            'name',
            'team',
            'annotations_types',
            'public',
            'base_format',
            'image_format',
            'annotation_format',
            'not_in_image_format',
            'vector_format',
            'name_format',
            'min_verifications',
            'image_aggregation',
            'include_blurred',
            'include_concealed',
        ]


class ExportFormatEditForm(forms.ModelForm):
    class Meta:
        model = ExportFormat
        fields = [
            'name',
            'annotations_types',
            'public',
            'base_format',
            'image_format',
            'annotation_format',
            'not_in_image_format',
            'vector_format',
            'name_format',
            'min_verifications',
            'image_aggregation',
            'include_blurred',
            'include_concealed',
        ]

src/imagetagger/base/views.py
from django.conf import settings
from django.shortcuts import redirect, render
from django.urls import reverse


def index(request):
    return redirect(reverse('images:index'))


def problem_report(request):
    if settings.PROBLEMS_TEXT != '':
        return render(request, 'base/problem.html', {
            'text': settings.PROBLEMS_TEXT
        })
    else:
        return redirect(settings.PROBLEMS_URL)

src/imagetagger/annotations/templates/annotations/annotationtypes.html
{% for annotation_type in annotation_types %}
  <option value="{{annotation_type.id}}" {% if forloop.counter <= 10 %} id="annotation_type_{{ forloop.counter }}"{% endif %} data-vector-type="{{ annotation_type.vector_type }}" data-node-count="{{ annotation_type.node_count }}" {% if annotation_type.id == last_annotation_type_id %} selected {% endif %} >
    {{annotation_type.name}}{% if forloop.counter <= 10 %} ({{ forloop.counter }}){% endif %}
  </option>
{% endfor %}

src/imagetagger/annotations/templates/annotations/base.html
{% extends 'base/base.html' %}
{% load static %}

{% block taggerimports %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/imgareaselect-default.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/cursor.css' %}" />
    {% block additional_annotation_css %}
    {% endblock additional_annotation_css %}
{% endblock %}

{% block additional_js %}
  <script type="text/javascript" src="{% static 'scripts/jquery.imgareaselect.pack.js' %}"></script>
  <script type="text/javascript" src="{% static 'scripts/jcanvas.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'scripts/jcanvas-handles.min.js' %}"></script>
  {% block additional_annotation_js %}
  {% endblock additional_annotation_js %}
{% endblock additional_js %}

{% block selectorblock %}
    <div id="crosshair-h" class="hair"></div>
    <div id="crosshair-v" class="hair"></div>
    <span id="mousepos" >(0,0)</span>
{% endblock %}
{% block navblock %} <li><a href="{% url 'images:view_imageset' selected_image.image_set_id %}">{{ selected_image.image_set.name }}</a></li> {% endblock %}

src/imagetagger/annotations/templates/annotations/create_exportformat.html
{% extends 'base/base.html' %}

{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block bodyblock %}
    <div class="container">
        <h2>Create new Exportformat:</h2>
            <form method="POST" action="{% url 'annotations:create_exportformat' %}{% if mode and id %}?mode={{ mode }}&id={{ id }}{% endif %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name"><h3>{{ form.name.label }}</h3> of the export format</label>
                    {% render_field form.name class+='form-control' %}
                    {% for error in form.name.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_team"><h3>{{ form.team.label }}</h3></label>
                    {% render_field form.team class+='form-control' %}
                    {% for error in form.team.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_name_format"><h3>{{ form.name_format.label }}</h3>for the export file name</label>
                    {% include 'annotations/export_format_legends/name.html' %}
                    {% render_field form.name_format class+='form-control' %}
                    {% for error in form.name_format.errors %}
                    <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_public"><h3>{{ form.public.label }}: </h3></label>
                    {% render_field form.public %}
                    {% for error in form.public.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_annotations_types"><h3>{{ form.annotations_types.label }}</h3></label>
                    {% blocktrans %}
                        <p>Hold down "Ctl" to select more than one.</p>
                    {% endblocktrans %}
                    {% render_field form.annotations_types class+='form-control' %}
                    {% for error in form.annotations_types.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_min_verifications"><h3>Minimum Amount of Verifications needed:</h3></label>
                    {% render_field form.min_verifications %}
                    {% for error in form.min_verifications.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_include_blurred"><h3>{{ form.include_blurred.label }} annotations: </h3></label>
                    {% render_field form.include_blurred %}
                    {% for error in form.include_blurred.errors %}
                       <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_include_concealed"><h3>{{ form.include_concealed.label }} annotations: </h3></label>
                    {% render_field form.include_concealed %}
                    {% for error in form.include_concealed.errors %}
                    <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                    </div>
                <hr>
                <div class="form-group">
                    <label for="id_base_format"><h3>{{ form.base_format.label }}</h3></label>
                    {%  include 'annotations/export_format_legends/base.html' %}
                    {% render_field form.base_format class+='form-control'%}
                    {% for error in form.base_format.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <hr>
                <div class="form-group">
                    <label for="id_image_aggregation"><h3>Group annotations by images: </h3></label>
                    {% render_field form.image_aggregation|append_attr:'id:img_agg' %}
                </div>
                <div class="form-group" id="img_form-group" style="display: none;">
                    <label for="id_image_format"><h3>{{ form.image_format.label }}</h3></label>
                    {% include 'annotations/export_format_legends/image.html' %}
                    {% render_field form.image_format class+='form-control'%}
                    {% for error in form.image_format.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <hr>
                <div class="form-group">
                    <label for="id_annotation_format"><h3>{{ form.annotation_format.label }}</h3></label>
                    {%  include 'annotations/export_format_legends/annotation.html' %}
                    {% render_field form.annotation_format class+='form-control'%}
                    {% for error in form.annotation_format.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <hr>
                <div class="form-group">
                    <label for="id_vector_format"><h3>{{ form.vector_format.label }}</h3></label>
                    {% include 'annotations/export_format_legends/vector.html' %}
                    {% render_field form.vector_format class+='form-control'%}
                    {% for error in form.vector_format.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                <hr>
                <div class="form-group">
                    <label for="id_not_in_image_format"><h3>{{ form.not_in_image_format.label }}</h3></label>
                    {% include 'annotations/export_format_legends/not_in_image.html' %}
                    {% render_field form.not_in_image_format class+='form-control'%}
                    {% for error in form.not_in_image_format.errors %}
                        <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                </div>
                {% for error in form.non_field_errors %}
                    <div class="alert alert-warning">{{ error }}</div>
                {% endfor %}
                <input type="submit" value="{% trans 'Create Format' %}" class="btn btn-primary" />
            </form>
        </div>
        <p></p>
    </div>
    {% block additional_js %}<script type="text/javascript" src="{% static 'annotations/js/export_creation.js' %}"></script>{% endblock %}
{% endblock bodyblock %}

src/imagetagger/annotations/templates/annotations/manage_annotations.html
{% extends 'base/base.html' %}
{% load static %}
{% load update_query %}
{% block navblock %}
<li><a href='{% url 'images:view_imageset' selected_image_set.id %}'>Imageset</a></li>
{% endblock %}
{% block additional_js %}
<script type="text/javascript" src="{% static 'annotations/js/manage_annotations.js' %}"></script>
{% endblock additional_js %}
{% block bodyblock %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h1>Manage annotations of {% if selected_image_set.team %} <a href="{% url 'users:team' selected_image_set.team_id%}">{{selected_image_set.team.name}}</a>/{% endif %}<a href="{% url 'images:view_imageset' selected_image_set.id %}">{{selected_image_set.name}}</a></h1>
            {% if annotations.has_other_pages %}
                <h4>
                    Page {{ annotations.number }} of {{ annotations.paginator.num_pages }}
                </h4>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <form method="get" class="col-md-6">
                    <div class="input-group annotation-filter" role="group" aria-label="annotation-filter">
                        <select class="form-control" id="annotation-filter-select" name="filter">
                            <option value="annotation-type" {% if filter == 'annotation-type' %} selected {% endif %}>Annotation type</option>
                            <option value="latest-change-by" {% if filter == 'latest-change-by' %} selected {% endif %}>Latest change by ...</option>
                            <option value="newer-than" {% if filter == 'newer-than' %} selected {% endif %}>Newer than ...</option>
                            <option value="older-than" {% if filter == 'older-than' %} selected {% endif %}>Older than ...</option>
                            <option value="verifications-min" {% if filter == 'verifications-min' %} selected {% endif %}>Minimum number of verifications</option>
                            <option value="verifications-max" {% if filter == 'verifications-max' %} selected {% endif %}>Maximum number of verifications</option>
                        </select>
                        <input type="text" class="form-control" id="annotation-filter-input" name="value" value="{% if value is not None and value != '' %}{{ value }}{% endif %}"/>
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-filter"></span>
                            </button>
                            <a href="{% url 'annotations:manage_annotations' selected_image_set.id %}" class="btn btn-danger">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                        </span>
                    </div>
                </form>
                {% if delete_permission and annotation_count > 0 %}
                <button type="button" class="btn btn-danger delete-annotations" data-toggle="modal" data-target="#deleteModal{{ tool.id }}">
                    {% if value is None or value == '' %}
                        Delete all annotations
                    {% else %}
                        Delete all filtered annotations
                    {% endif %}
                </button>
                {% endif %}
                <table class="table table-striped" width='100%'>
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Type</th>
                            <th>Annotation</th>
                            <th>Verifications</th>
                            <th>Creator</th>
                            <th>Last editor</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    {% for annotation in annotations %}
                        <tr>
                            <td><a href='{% url 'annotations:annotate' annotation.image.id %}'>{{ annotation.image.name }}</a></td>
                            <td>{{ annotation.annotation_type.name }}</td>
                            <td>{{ annotation.content | truncatechars:60}}{% if annotation.blurred %} <span id="blurred_label" class="label label-info">Blurred</span>{% endif %}{% if annotation.concealed %} <span id="concealed_label" class="label label-warning">Concealed</span>{% endif %}</td>
                            <td>
                                {% if annotation.verification_difference %}
                                    {{ annotation.verification_difference }}
                                {% else %}
                                    0
                                {% endif %}
                            </td>
                            <td>{{ annotation.user.username }}</td>
                            <td>{{ annotation.last_editor.username }}</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="btn-group">
                                    <a class="btn btn-success" href='{% url 'annotations:annotate' annotation.image.id %}?edit={{ annotation.id }}'>
                                            <span class="glyphicon glyphicon-pencil glyphicon-white" aria-hidden="true"></span>
                                    </a>
                                    <a class="btn btn-warning" href='{% url 'annotations:verify' annotation.id %}'>
                                            <span class="glyphicon glyphicon-ok glyphicon-white" aria-hidden="true"></span>
                                    </a>
                                    <a class="btn btn-danger" href='{% url 'annotations:delete_annotation' annotation.id%}'>
                                            <span class="glyphicon glyphicon-trash glyphicon-white" aria-hidden="true"></span>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="pagination">
                <span class="step-links">
                    <div class="btn-group" role="group" aria-label="btn-group">
                        {% if annotations.has_previous %}
                            <a class="btn btn-default" href="?{% update_query page=1 %}">&laquo; first</a>
                            <a class="btn btn-default" href="?{% update_query page=annotations.previous_page_number %}">previous</a>
                        {% endif %}
                        {% if annotations.has_other_pages %}
                            <span class="current btn btn-default">
                                Page {{ annotations.number }} of {{ annotations.paginator.num_pages }}
                            </span>
                        {% endif %}
                        {% if annotations.has_next %}
                            <a class="btn btn-default" href="?{% update_query page=annotations.next_page_number %}">next</a>
                            <a class="btn btn-default" href="?{% update_query page=annotations.paginator.num_pages %}">last &raquo;</a>
                        {% endif %}
                    </div>
                </span>
            </div>
        </div>
    </div>
</div>
{% if delete_permission and annotation_count > 0 %}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">
                    {% if annotation_count == 1 %}
                        Delete {{ annotation_count }} annotation
                    {% else %}
                        Delete {{ annotation_count }} annotations
                    {% endif %}
                    </h4>
                </div>
                <div class="modal-body">
                    {% if annotation_count == 1 %}
                        Do you really want to delete {{ annotation_count }} annotation?
                    {% else %}
                        Do you really want to delete {{ annotation_count }} annotations?
                    {% endif %}
                </div>
                <div class="modal-footer">
                    <form method="post" action="{% url 'annotations:delete_annotations' selected_image_set.id %}">
                        {% csrf_token %}
                        <div class="input-group delete-annotations" role="group" aria-label="delete-annotations">
                            <input type="hidden" name="filter" value="{{ filter }}">
                            <input type="hidden" name="value" value="{{ value }}">
                            <button type="submit" class="btn btn-danger">Yes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endif %}
{% endblock %}